### ISSUE TITLE
Legacy javascript -> ES6

### ISSUE THREAD

**Issue by jonaylor89** [jonaylor89/BrowserGames#1]
I've already done a little bit of refactoring to es6 but there is some work that needs to be done

**Comment by vindu939** [comment]
@jonaylor89 I can help with the refactoring, please let me know where can I contribute.

**Comment by ktan114** [comment]
I'd like to help out too if you don't mind.

**Comment by ktan114** [comment]
I started on the SnakeGame folder.

**Comment by ays14** [comment]
@jonaylor89  I'm working on the folders starting with F and M.

**Comment by jonaylor89** [comment]
There are still some files that aren't es6 yet. I plan on refactoring it this weekend but I'm going to leave this issue open in case someone wants to get a pull request in for hacktoberfest
